# Generated by Django 4.2.26 on 2025-11-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_accesspass_options_remove_accesspass_status_and_more'),
        ('guests', '0003_alter_booking_options_remove_booking_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
