# Generated by Django 4.2.26 on 2025-11-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guest_check_in_remove_guest_check_out_and_more'),
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_created', 'لم تُنشأ'), ('active', 'مفعّلة'), ('cancelled', 'ملغاة'), ('expired', 'منتهية')], default='not_created', max_length=20)),
                ('wallet_pass_id', models.CharField(blank=True, help_text='المعرّف القادم من Apple Wallet أو نظام القفل', max_length=255)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_pass', to='guests.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='DoorPass',
        ),
    ]
