# Generated by Django 4.2.26 on 2025-11-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
        ('passes', '0002_accesspass_delete_doorpass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspass',
            options={'verbose_name': 'Access Pass', 'verbose_name_plural': 'Access Passes'},
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='status',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='wallet_pass_id',
        ),
        migrations.AddField(
            model_name='accesspass',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='وقت انتهاء صلاحية البطاقة إن وجد', null=True),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل البطاقة مفعّلة الآن؟'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='pass_id',
            field=models.CharField(blank=True, help_text='معرف البطاقة في النظام أو في Apple Wallet (إن وجد)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='wallet_url',
            field=models.URLField(blank=True, help_text='رابط تحميل البطاقة في المحفظة', null=True),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='booking',
            field=models.OneToOneField(help_text='الحجز المرتبط بهذه البطاقة', on_delete=django.db.models.deletion.CASCADE, related_name='access_pass', to='core.booking'),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='وقت إنشاء البطاقة'),
        ),
    ]
